#version: '3.4' #ver overrride

services:
  codigospostales_net:
    image: ${DOCKER_REGISTRY-}codigospostalesnet
    build:
      context: .
      dockerfile: CodigosPostales/Dockerfile
    depends_on:
        - mongodb  # Esto asegura que MongoDB esté listo antes de iniciar el servicio clientesms
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    #container_name: mongodb
    ports:
      - "27017:27017"  # Mapea el puerto para acceder a MongoDB desde fuera del contenedor
    environment:      
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - app-network

networks:
  app-network:
    driver: bridge