version: '3.4'

services:
  codigospostales_net:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    #- ASPNETCORE_URLS=https://+:443;http://+:80
    - ASPNETCORE_URLS=http://+:80
    ports:
      #- "80"
      #- "443"
      - "8480:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro